public-bookmarks-rails/config/routes.rb
Rails.application.routes.draw do
  resources :public_bookmarks, except: [:edit, :update] do
    get :index_authenticated, on: :collection
  end

  root 'hello_world#index'
end

public-bookmarks-rails/app/models/public_bookmark.rb
class PublicBookmark < ActiveRecord::Base
end

public-bookmarks-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

public-bookmarks-rails/app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
  def index
  end
end

public-bookmarks-rails/app/controllers/public_bookmarks_controller.rb
class PublicBookmarksController < ApplicationController
  before_action :set_public_bookmark, only: [:show, :destroy]
  before_action :set_public_bookmarks, only: [:index_authenticated, :index]
  http_basic_authenticate_with name: HTTP_BASIC_AUTH['name'], password: HTTP_BASIC_AUTH['password'], only: [:index_authenticated, :destroy]

  def index_authenticated
    @authenticated = true
    render :index
  end

  # GET /public_bookmarks
  # GET /public_bookmarks.json
  def index
  end

  # GET /public_bookmarks/1
  # GET /public_bookmarks/1.json
  def show
  end

  # GET /public_bookmarks/new
  def new
    @public_bookmark = PublicBookmark.new
  end

  # POST /public_bookmarks
  # POST /public_bookmarks.json
  def create
    @public_bookmark = PublicBookmark.new(public_bookmark_params)

    respond_to do |format|
      if @public_bookmark.save
        format.html { redirect_to @public_bookmark, notice: 'Public bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @public_bookmark }
      else
        format.html { render :new }
        format.json { render json: @public_bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /public_bookmarks/1
  # DELETE /public_bookmarks/1.json
  def destroy
    @public_bookmark.destroy
    respond_to do |format|
      format.html { redirect_to index_authenticated_public_bookmarks_url, notice: 'Public bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_public_bookmark
      @public_bookmark = PublicBookmark.find(params[:id])
    end

    def set_public_bookmarks
      @public_bookmarks = PublicBookmark.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def public_bookmark_params
      params.require(:public_bookmark).permit(:title, :url, :description, :submitter_email)
    end
end

public-bookmarks-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

public-bookmarks-rails/app/views/hello_world/index.html.erb
<%= ['Hello', 'Hi', 'Hey', 'Yo'][rand(4)] %> World!

public-bookmarks-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PublicBookmarksRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

public-bookmarks-rails/app/views/public_bookmarks/_form.html.erb
<%= form_for(@public_bookmark) do |f| %>
  <% if @public_bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@public_bookmark.errors.count, "error") %> prohibited this public_bookmark from being saved:</h2>

      <ul>
      <% @public_bookmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :submitter_email %><br>
    <%= f.text_field :submitter_email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

public-bookmarks-rails/app/views/public_bookmarks/index.html.erb
<h1>Listing public_bookmarks</h1>

<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Description</th>
      <th>Submitter email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @public_bookmarks.each do |public_bookmark| %>
      <tr>
        <td><%= public_bookmark.title %></td>
        <td><%= public_bookmark.url %></td>
        <td><%= public_bookmark.description %></td>
        <td><%= public_bookmark.submitter_email %></td>
        <td><%= link_to 'Show', public_bookmark %></td>
        <% if @authenticated %>
          <td><%= link_to 'Destroy', public_bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Public bookmark', new_public_bookmark_path %>

public-bookmarks-rails/app/views/public_bookmarks/new.html.erb
<h1>New public_bookmark</h1>

<%= render 'form' %>

<%= link_to 'Back', public_bookmarks_path %>

public-bookmarks-rails/app/views/public_bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @public_bookmark.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @public_bookmark.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @public_bookmark.description %>
</p>

<p>
  <strong>Submitter email:</strong>
  <%= @public_bookmark.submitter_email %>
</p>

<%= link_to 'Back', public_bookmarks_path %>